// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDljSzRD30P83Zn-Y-pSGKZZWCn8HRreI8',
    appId: '1:842408371807:web:5d2bcda003fc9dce81ddea',
    messagingSenderId: '842408371807',
    projectId: 'savaan-6de02',
    authDomain: 'savaan-6de02.firebaseapp.com',
    storageBucket: 'savaan-6de02.firebasestorage.app',
    measurementId: 'G-16CK9H313G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOoXkCTR_3zXg8tXCNP5ebVlQw-pDie8I',
    appId: '1:842408371807:android:9010b875aa310a7581ddea',
    messagingSenderId: '842408371807',
    projectId: 'savaan-6de02',
    storageBucket: 'savaan-6de02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALow6HFOdOPKsXW7tnmn5z_xQNqGquBYs',
    appId: '1:842408371807:ios:b6881846b4cdddd881ddea',
    messagingSenderId: '842408371807',
    projectId: 'savaan-6de02',
    storageBucket: 'savaan-6de02.firebasestorage.app',
    iosBundleId: 'com.savaan.savaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALow6HFOdOPKsXW7tnmn5z_xQNqGquBYs',
    appId: '1:842408371807:ios:b6881846b4cdddd881ddea',
    messagingSenderId: '842408371807',
    projectId: 'savaan-6de02',
    storageBucket: 'savaan-6de02.firebasestorage.app',
    iosBundleId: 'com.savaan.savaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDljSzRD30P83Zn-Y-pSGKZZWCn8HRreI8',
    appId: '1:842408371807:web:2e4ced299ebc075981ddea',
    messagingSenderId: '842408371807',
    projectId: 'savaan-6de02',
    authDomain: 'savaan-6de02.firebaseapp.com',
    storageBucket: 'savaan-6de02.firebasestorage.app',
    measurementId: 'G-XSF6VY2S78',
  );
}
